### ISSUE TITLE
Zielvorstellung für den SDK-Webserver erarbeiten

### ISSUE THREAD

**Issue by MartinGauk** [questionpy-org/questionpy-sdk#102]
Die Seiten haben sich irgendwie ergeben, aber wir haben uns nie Gedanken gemacht, wie es am Ende wirklich aussehen soll. Bitte überlege daher mal, wie die Seiten, die durch den SDK-Webserver bereitgestellt werden, aussehen und welche Funktionen sie bieten sollten. Zeichne ruhig ein beispielhaftes Design der Seiten auf.

Über den Webserver soll man ein einzelnes Paket ausprobieren/testen können.
Meine Gedanken aktuell:
- Frage erstellen/bearbeiten
  - mehrere Fragen können gespeichert werden
  - Aufruf technischer Daten (z.B. der Inhalt des `question_state`)
  - Speicherort für `question_state` und dazugehörige `question_state_files` + mögliche User-Uploads in Options (ggf. mehrere, z.B. `~/.config/questionpy-sdk`, der aktuelle Ordner?, im Paket?)
    - Eine Überlegung von mir war mal, dass man auch im Paket selber Presets speichern könnte, die im LMS auswählbar sind
- Frage aufrufen/beantworten:
  - Auswahl der Variante
  - Abspeichern der Antworten erlauben, um verschiedene Antworten zu testen?
    - Speicherort für `attempt_state`, `score`, `scoring_state`, `scoring_files`
  - Orientierung an der Vorschau in Moodle, d.h.
    - der Versuch kann neu begonnen werden
    - (Zwischen-) Speicherung
    - die Felder mit den richtigen Antworten befüllen
    - Eingaben bewerten
    - nach einer Bewertung kann
      - neu bewertet werden
      - innerhalb dieses Versuchs die Frage neu beantworten (zum Testen von Mehrfachbeantwortungen und der Final Score Funktion)
    - Hinweis anfordern (sofern in der Frage `hints_available`)
  - Aufruf technischer Daten (z.B. `attempt_state`, `scoring_state`, die UI-XMLs)

Zudem sollte für beide Seiten die Sprache ausgewählt werden können, die an das Paket übermittelt wird.

**Comment by MartinGauk** [comment]
Ich möchte an das Issue erinnern. Mit der neuen Hinweis-Möglichkeit in #118 gibt es auch noch eine Idee, die in der Zielvorstellung berücksichtigt werden sollte. Bitte bespreche das auch mal kurz mit @janbritz .

**Comment by MartinGauk** [comment]
Hinweis bezüglich Speicherort der States: Mit #125 kann bei `questionpy-sdk run` das Argument `--state-storage-path` oder die Umgebungsvariable `QPY_STATE_STORAGE_PATH` verwendet werden, um den Speicherort bei Bedarf anzupassen.

**Comment by larsbonczek** [comment]
Ich habe eine Wiki-Seite mit dem besprochenen Mockup eingerichtet
