### ISSUE TITLE
Validierungsfehler bei hidden group

### ISSUE THREAD

**Issue by MartinGauk** [questionpy-org/questionpy-sdk#46]
Das aktuelle example bringt einen Validierungsfehler, wenn man das Formular nur mit den ausgefüllten Pflichtfeldern abschicken will.

```
1 validation error for MyModel
name_group
  field required (type=value_error.missing)
```

**Comment by MHajoha** [comment]
Sollte mit https://github.com/questionpy-org/questionpy-sdk/commit/2c7a083298f493fa3786b54aaead1fd87b22548f eigentlich schon gefixt sein. Kannst du das Paket nochmal mit der neusten SDK-Version bauen und nochmal ausprobieren?

**Comment by MartinGauk** [comment]
Stimmt, damit geht es.
